Fix for parenthesis error
Added parentheses as it was suggested by compiler.
error: suggest parentheses around operand of '!' or change '&' to '&&' or '!' to '~' [-Werror=parentheses]

(Cherry picked from commit c3ce224c622e064207d1aff03f2440ca19617b4a)

Signed-off-by: Arseniy Antonov <arseniy.antonov@intel.com>
Change-Id: Ic3746d9804488411d10d460ddfda11f1fad8efef